### ISSUE TITLE
rename to EDA?

### ISSUE THREAD

**Issue by djdanielsson** [redhat-cop/eda_configuration#2]
@Tompage1994 @sean-m-sullivan

**Comment by sean-m-sullivan** [comment]
I agree, but name?
event_driven_configuration?

**Comment by Tompage1994** [comment]
I agree we should think about making it but lets just use a new repo and get rid of this one. It's not that much effort to achieve. 

Presumably the EDA would be around the EDA server configuration in which case it could be worth waiting to see if it gets some kind of better name than eda-server

**Comment by sean-m-sullivan** [comment]
We are able to rename it at will, however based on https://github.com/redhat-cop/org/issues/562, it sometimes takes us 2 weeks to create new repos, IMO better to rename a now defunct one then wait 2+ weeks.

**Comment by djdanielsson** [comment]
done
